# report_generator.py

import subprocess
import sys
import argparse
import subprocess
import os
import time
import random
import threading
import re
import random
from urllib.parse import urlsplit
from utils import *
import pyfiglet
from class_color import *
from tools import *

def generate_report(rs_vul_list, target, date):
    debuglog = f"rs.dbg.{target}.{date}" 
    vulreport = f"rs.vul.{target}.{date}"

    print("[ Report Generation Phase Initiated. ]")
    if len(rs_vul_list) == 0:
        print("\tNo Vulnerabilities Detected.")
    else:
        with open(vulreport, "a") as report:
            for vul in rs_vul_list:
                vuln_info = vul.split('*')
                report.write(vuln_info[1])
                report.write("\n------------------------\n\n")
                temp_report_name = f"/tmp/Webscan_temp_{vuln_info[0]}"
                with open(temp_report_name, 'r') as temp_report:
                    data = temp_report.read()
                    report.write(data)
                    report.write("\n\n")

            print(f"\tComplete Vulnerability Report for {target} named {vulreport} is available under the same directory WebScan resides.")

        report.close()

    # Writing all scan files output into RS-Debug-ScanLog for debugging purposes.
    for file_index, file_name in enumerate(vulreport):
        with open(debuglog, "a") as report:
            try:
                with open(f"/tmp/rapidscan_temp_{file_name[0]}", 'r') as temp_report:
                    data = temp_report.read()
                    report.write(file_name[1])
                    report.write("\n------------------------\n\n")
                    report.write(data)
                    report.write("\n\n")
            except:
                break
        report.close()
    print("[ Report Generation Phase Completed. ]")
    print("\tTotal Number of Vulnerability Checks        : "+bcolors.BOLD+bcolors.OKGREEN+str(len(tool_names))+bcolors.ENDC)
    print("\tTotal Number of Vulnerability Checks Skipped: "+bcolors.BOLD+bcolors.WARNING+str(rs_skipped_checks)+bcolors.ENDC)
    print("\tTotal Number of Vulnerabilities Detected    : "+bcolors.BOLD+bcolors.BADFAIL+str(len(rs_vul_list))+bcolors.ENDC)
    print("\tTotal Time Elapsed for the Scan             : "+bcolors.BOLD+bcolors.OKBLUE+display_time(int(rs_total_elapsed))+bcolors.ENDC)
    print("\n")
    print("\tFor Debugging Purposes, You can view the complete output generated by all the tools named "+bcolors.OKBLUE+debuglog+bcolors.ENDC+" under the same directory.")
    print(bcolors.BG_ENDL_TXT+"[ Report Generation Phase Completed. ]"+bcolors.ENDC)

    os.system('setterm -cursor on')
    os.system('rm /tmp/Webscan_te* > /dev/null 2>&1') # Clearing previous scan files

